# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0002_auto_20180226_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cottage',
            fields=[
                ('cottageid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('addr1', models.CharField(blank=True, max_length=128)),
                ('views', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Cottages',
            },
        ),
    ]
