# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0005_cottage_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cottage',
            old_name='bio',
            new_name='desc',
        ),
    ]
