# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0006_auto_20180226_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottage',
            name='desc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
