# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0008_auto_20180226_1945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Cottage',
        ),
        migrations.AlterModelOptions(
            name='cottage',
            options={'verbose_name_plural': 'cottages'},
        ),
    ]
