# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0009_auto_20180226_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cottage',
            name='likes',
        ),
    ]
