# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0011_cottage_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cottage',
            old_name='category',
            new_name='host',
        ),
    ]
