# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0013_auto_20180226_1954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='UserProfile',
        ),
    ]
