# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0017_auto_20180226_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='usertype',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
