# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0018_auto_20180303_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='usertype',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
