# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0022_auto_20180303_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottage',
            name='region',
            field=models.CharField(choices=[('aberdeenshire', 'Aberdeenshire'), ('argyll', 'Argyll'), ('ayrshire', 'Ayrshire'), ('dumfries-and-galloway', 'Dumfries & Galloway'), ('angus', 'Angus'), ('edinburgh', 'Edinburgh'), ('fife', 'Fife'), ('glasgow', 'Glasgow'), ('highlands', 'Highlands'), ('loch-lomond', 'Loch Lomond / Trossachs'), ('orkney', 'Orkney'), ('outer-hebrides', 'Outer Hebrides'), ('perthshire', 'Perthshire'), ('scottish-borders', 'Scottish Borders'), ('shetland', 'Shetland')], max_length=128),
        ),
    ]
