# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0023_auto_20180303_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='price_from',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='cottage',
            name='price_to',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='picture',
            field=models.ImageField(blank=True, upload_to='cottage_images'),
        ),
    ]
