# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0025_cottage_sleeps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cottage',
            options={},
        ),
        migrations.RenameField(
            model_name='cottage',
            old_name='addr1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='cottage',
            name='addr2',
        ),
        migrations.RemoveField(
            model_name='cottage',
            name='addr3',
        ),
        migrations.RemoveField(
            model_name='cottage',
            name='host',
        ),
        migrations.RemoveField(
            model_name='cottage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cottage',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='cottage',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='cottage',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='cottage',
            name='price_from',
        ),
        migrations.RemoveField(
            model_name='cottage',
            name='price_to',
        ),
        migrations.RemoveField(
            model_name='cottage',
            name='sleeps',
        ),
        migrations.RemoveField(
            model_name='cottage',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='usertype',
        ),
        migrations.AddField(
            model_name='cottage',
            name='title',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog.Region'),
        ),
    ]
