# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0026_auto_20180308_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cottage',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='cottage',
            name='image',
            field=models.ImageField(blank=True, upload_to='cottages'),
        ),
        migrations.AddField(
            model_name='cottage',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
