# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0029_auto_20180310_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cottage',
            name='slug',
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
