# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0030_auto_20180310_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
