# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0032_auto_20180317_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
